apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- advanced-cluster-management/operator/overlays/release-2.8
- openshift-gitops-operator/operator/overlays/latest
- openshift-pipelines-operator/overlays/latest
- rhods-operator/operator/overlays/stable
